quarkus:
  http:
    port: 8080
    host: localhost
    limits:
      max-body-size: 200M
    body:
      preallocate-body-buffer: true
  datasource:
    db-kind: h2
    jdbc:
      url: jdbc:h2:./target/output/myDb;create=true
  hibernate-orm:
    log:
      sql: true
    database:
      generation: update
